# -*- coding: utf-8 -*-
"""ANN_test

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ttLEaaEqJyDCDz7_CHilmWlVMXghOvcR
"""

import seaborn as sns
import pandas as pd
import numpy as np

df=sns.load_dataset('iris')
df.head()

df['species'].unique()

df.isnull().sum()

df=df[df['species']!='setosa']

df.head()

df['species']=df['species'].map({'versicolor':0,'virginica':1})
df.head()

X=df.iloc[:,:-1]
y=df.iloc[:,-1]

X

y

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

from keras.models import Sequential
from keras.layers import Dense
from joblib.parallel import SequentialBackend
input_dim= len(X_train.columns)
neurons= 64
epochs=100
model= Sequential()

clf.fit(X_train, y_train)

model.add(Dense(neurons,input_dim=input_dim,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

history= model.fit(X_train,y_train,epochs=epochs,verbose=1, validation_split=0.33)